### PR TITLE
Compatibility fix for .noConflict()

### PR DESCRIPTION
**Pull request by ghost**
Added local alias $ = jQuery in CoffeeScript source; Updated demo html
files to easily verify compatibility with .noConflict(); Updated source
of jQuery to Google CDN

### CODE REVIEW

**Comment by ghost** [comment]
@indyplanets It seems there's an older reported issue that this fix resolves,   `#40 doesn't work in noConflict mode`  (tagged as `Feature Request`). Somehow I missed that, but at least now it could be closed.
In regards to switching the CDN for jQuery, it's just a personal preference, I trust Google CDN's reliability more than MediaTemple's CDN.

**Comment by mrjasonweaver** [comment]
This is great. Thanks @pallandt! Give me some time to review and I'll merge. Super busy at the moment.

**Comment by mrjasonweaver** [comment]
@pallandt There's a few other items I'm working on at the moment as well. I'll pull this in and make a new release with all my new stuff. Might make this a v1.0 release if all goes well. Thanks for your help.

**Comment by ghost** [comment]
@indyplanets No problem, you're welcome and take your time. Thanks for creating the project in the 1st place.

**Comment by mrjasonweaver** [comment]
This is being merged with the release of version 1.0: https://github.com/indyplanets/flexnav/pull/56

Thanks for your work on this: :rocket: :+1: :beers:

**Pull request closed without merging**
