### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by thebitguru**
Hi Jason,

I am using [bower](http://bower.io/) as the package manager for a project.  I am hoping that you can add official support for it so I went ahead and created the bower.json file for it.  This was my first bower package so I tried it out by registering in bower registry under `flexnav`.  You can find more info at [registering packages](https://github.com/bower/bower#registering-packages).

Once you have merged this in then we will have to request that they delete my registration and allow you to register (`bower register flexnav https://github.com/indyplanets/flexnav`).

Thanks!
Farhan

### CODE REVIEW

**Comment by mrjasonweaver** [comment]
@thebitguru Looks good. Thanks!

**Comment by mrjasonweaver** [comment]
@thebitguru Could you request to unregister and I'll register with the official git repo?

**Comment by thebitguru** [comment]
Requested.  https://github.com/bower/bower/issues/120

**Comment by thebitguru** [comment]
Looks like it [has been removed](https://github.com/bower/bower/issues/120#issuecomment-28128427).  I will delete my fork.  Thanks!

**Comment by mrjasonweaver** [comment]
@thebitguru Cool. I've registered the official git repo. thanks!

**Pull request merged**
